name: Build Netbare-Core Android Library
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: 28
      - name: Grant permissions for Android SDK
        run: |
          chmod +x $ANDROID_HOME/tools/bin/sdkmanager
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
      - name: Install Android dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
      - name: Build the Android library
        run: |
          cd netbare-core
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: netbare-core-aar
          path: netbare-core/build/outputs/aar/netbare-core-release.aar
