name: Build Netbare-Core Android Library
on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'JDK version'
        required: true
        default: '11'
      sdk-version:
        description: 'Android SDK version'
        required: true
        default: '28'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ github.event.inputs.java-version }}
          distribution: 'temurin'

      - name: Install expect
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: ${{ github.event.inputs.sdk-version }}

      - name: Grant permissions for Android SDK
        run: |
          chmod +x $ANDROID_HOME/tools/bin/sdkmanager
          expect -c '
            spawn $ANDROID_HOME/tools/bin/sdkmanager --licenses
            expect {
              "y/n" { send "y\r"; exp_continue }
              eof
            }
          '

      - name: Install Android dependencies
        run: |
          sudo dpkg --add-architecture i386  # 启用32位架构支持
          sudo apt-get update
          sudo apt-get install -y libc6-i386 libncurses5 libbz2-dev  # 修改为正确的包名
          sudo apt-get install -y openjdk-11-jdk-headless

      - name: Build the Android library
        run: |
          cd netbare-core
          ./gradlew assembleRelease
 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: netbare-core-aar
          path: netbare-core/build/outputs/aar/netbare-core-release.aar
