name: Build Netbare-Core Android Library

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'JDK version'
        required: true
        default: '11'
      sdk-version:
        description: 'Android SDK version'
        required: true
        default: '28'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ github.event.inputs.java-version }}
          distribution: 'temurin'  # 添加 distribution 参数

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: ${{ github.event.inputs.sdk-version }}

      - name: Grant permissions for Android SDK
        run: |
          chmod +x $ANDROID_HOME/tools/bin/sdkmanager
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - name: Install Android dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386

      - name: Build the Android library
        run: |
          cd netbare-core
          ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: netbare-core-aar
          path: netbare-core/build/outputs/aar/netbare-core-release.aar
